apiVersion: template.app.sealos.io/v1beta1
kind: Template
metadata:
  name: ${{ defaults.app_name }}
spec:
  title: '聚量猩球'
  url: 'https://www.matrixgorilla.com/'
  github: 'https://github.com/hello-stars/MatrixGorilla.git'
  author: 'sealos'
  description: '多年服务500强企业体验管理经验沉淀，聚量猩球XM提供高效便捷的智能在线问卷系统、智能标签引擎及VR拟真实验能力，全面覆盖趋势洞察、概念验证、产品研发、产品试销、精益上市过程中的所有场景，让企业多快好省地获取消费者体验数据，降低企业生产投资决策风险，让每个研发决策反向赋能市场销售，实现口碑及业绩的双增长!'
  readme: 'https://github.com/hello-stars/MatrixGorilla.git/main/README.md'
  icon: 'https://www.matrixgorilla.com/assets/images/logo/dark.png'
  template_type: inline
  defaults:
    app_name:
      type: string
      value: MatrixGorilla-${{ random(8) }}
    app_host:
      type: string
      value: ${{ random(8) }}
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matrixgorilla-api
  annotations:
    originImageName: matrixgorilla-api
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: matrixgorilla-api
    app: matrixgorilla-api
    cloud.sealos.io/deploy-on-sealos: matrixgorilla-api
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 10
  serviceName: matrixgorilla-api
  selector:
    matchLabels:
      app: matrixgorilla-api
  template:
    metadata:
      labels:
        app: matrixgorilla-api
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: matrixgorilla-api
          image: >-
            registry.cn-beijing.aliyuncs.com/juliangxingqiu/sealos-java-api:latest
          resources:
            requests:
              cpu: 100m
              memory: 102Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          command: [ ]
          args: [ ]
          ports:
            - containerPort: 15022
          imagePullPolicy: Always

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matrixgorilla-web
  annotations:
    originImageName: matrixgorilla-web
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: matrixgorilla-web
    app: matrixgorilla-web
    cloud.sealos.io/deploy-on-sealos: matrixgorilla-web
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 10
  serviceName: matrixgorilla-web
  selector:
    matchLabels:
      app: matrixgorilla-web
  template:
    metadata:
      labels:
        app: matrixgorilla-web
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: matrixgorilla-web
          image: >-
            registry.cn-beijing.aliyuncs.com/juliangxingqiu/sealos-java-web:latest
          resources:
            requests:
              cpu: 100m
              memory: 102Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          command: [ ]
          args: [ ]
          ports:
            - containerPort: 80
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: matrixgorilla-web
  labels:
    cloud.sealos.io/app-deploy-manager: matrixgorilla-web
    cloud.sealos.io/deploy-on-sealos: matrixgorilla-web
spec:
  ports:
    - port: 80
  selector:
    app: matrixgorilla-web

---
apiVersion: v1
kind: Service
metadata:
  name: matrixgorilla-api
  labels:
    cloud.sealos.io/app-deploy-manager: matrixgorilla-api
    cloud.sealos.io/deploy-on-sealos: matrixgorilla-api
spec:
  ports:
    - port: 15022
  selector:
    app: matrixgorilla-api

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matrixgorilla-web
  labels:
    cloud.sealos.io/app-deploy-manager: matrixgorilla-web
    cloud.sealos.io/app-deploy-manager-domain: matrixgorilla-web
    cloud.sealos.io/deploy-on-sealos: matrixgorilla-web
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/client-body-buffer-size: 1024m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 1024m
spec:
  rules:
    - host: MatrixGorilla-go.cloud.sealos.top
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: matrixgorilla-web
                port:
                  number: 80
          - pathType: Prefix
            path: /api
            backend:
              service:
                name: matrixgorilla-api
                port:
                  number: 15022

  tls:
    - hosts:
        - MatrixGorilla-go.cloud.sealos.top
      secretName: wildcard-cert
